### ISSUE TITLE
time played issue when played less than an hour

### ISSUE THREAD

**Issue by sybenx** [Mafrans/StadiaPlusDB#5]
https://stadiaplus.dev/profile/Syben/0000/games

The game is correctly sorted at the bottom of my played games list, but incorrectly displays '26h m" instead of "0h 26m"

![image](https://user-images.githubusercontent.com/2048087/92412095-ce835500-f107-11ea-9899-57ae73c834a3.png)

**Comment by Mafrans** [comment]
Thanks, will make sure to take a look at this!

**Comment by Mafrans** [comment]
This is solved as of 854fd38
